name: Generate GitHub Trophies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  generate-trophies:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: code-with-raiden
          output_path: .github/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: radical

      - name: Commit trophy SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .github/trophy.svg

          git diff --cached --quiet || git commit -m "Update GitHub trophies"

          git push
